### ISSUE TITLE
Escape bei verschiedenen Fenstern

### ISSUE THREAD

**Issue by jan-okke** [Summit-Sync/frontend#57]
Es lassen sich nicht alle Fenster per Escape schließen
(nur Kursvorlage, Kurs, Gruppenvorlage, Gruppe)

**Comment by jan-okke** [comment]
Weitere Fenster sind auch inkonsistant, z.B. lässt sich bei der Gruppe die Details auch per Escape schließen aber das Bearbeiten nicht

**Comment by Flavia-de-Luce** [comment]
Gefixt.
Alle Dialog die Werte vom Nutzer entgegen nehmen schließen sich nur über knöpfe oder mit ESC.
Andere Dialoge können auch durch klicken außerhalb des Dialoges geschlossen werden
