### ISSUE TITLE
canceled Course filter

### ISSUE THREAD

**Issue by 700Noel** [Summit-Sync/frontend#59]
add filter for canceled/not canceled courses

**Comment by 700Noel** [comment]
Oh ok, kannst du natürlich trotzdem machen wenn du willst

**Comment by Flavia-de-Luce** [comment]
Ist es mittlerweile, ich bin es am Implementieren :)

**Comment by Flavia-de-Luce** [comment]
Bei Gruppen gibt es noch den Fehler mit dem Backend...
