### ISSUE TITLE
Fehlende / Inkorrekte Validierung beim Gruppenkürzel im Frontend

### ISSUE THREAD

**Issue by jan-okke** [Summit-Sync/frontend#60]
Beim Erstellen einer Gruppenvorlage lässt sich beim Gruppenkürzel ein invalider Text wie z.B. "Das Kürzel" eingeben, beim Speichern kommt dann (wie erwartet) vom Backend ein Bad Request aber im Frontend passiert nichts (keine Fehlermeldung, keine Anzeige für den Nutzer dass die Validierung falsch war)

Gleiches beim Bearbeiten

**Comment by jan-okke** [comment]
gleiches für die Kursvorlage

**Comment by jan-okke** [comment]
bei der Kursvorlage ist es noch schlimmer, die Maske schließt sich komplett ohne Rückmeldung, sodass der Nutzer denkt dass die Vorlage angelegt worden wäre, wenn in Wirklichkeit ein Bad Request kam

**Comment by Flavia-de-Luce** [comment]
Ist bei beiden gefixt.
![image](https://github.com/Summit-Sync/frontend/assets/76540879/18bc9a75-2c1f-4b79-8b9a-b589e3a5e628)
