### ISSUE TITLE
Kurse und Gruppen können mehrfach abgesagt werden

### ISSUE THREAD

**Issue by jan-okke** [Summit-Sync/frontend#65]
Soll es wirklich möglich sein, Kurse / Gruppen abzusagen, welche bereits abgesagt worden sind?

**Comment by Flavia-de-Luce** [comment]
Das ist tatsächlich auch ein Backend issue, da dort der Wert nicht weggeschrieben wird / wurde.
Des weiteren sortieren wir nicht nach den Flags...
